<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Azure.Identity" Version="1.12.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.5" />
	  <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.5" />
	  <PackageReference Include="Microsoft.Identity.Client" Version="4.72.0" />
  </ItemGroup>

</Project>
