// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RDS.ExpenseTracker.Infrastructure;

#nullable disable

namespace RDS.ExpenseTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ExpenseTrackerContext))]
    [Migration("20260713143410_Make_Account_UserId_Required")]
    partial class Make_Account_UserId_Required
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RDS.ExpenseTracker.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("RDS.ExpenseTracker.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Other",
                            IsDefault = true,
                            Name = "Default",
                            Tags = "default"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Money transfers",
                            Name = "Money tranfers"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Salary or other work incomes",
                            Name = "Work incomes"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Rent, utilities, home maintenance, etc",
                            Name = "Housing"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Health expenses, gym, sports, etc.",
                            Name = "Health & Fitness"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Food and bevarage",
                            Name = "Food and bevarage"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Transportation, car maintenance and insurance, fuel, etc.",
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Entertainment",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Clothes and accessories",
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Savings and investments",
                            Name = "Savings and investments"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Gifts",
                            Name = "Gifts"
                        });
                });

            modelBuilder.Entity("RDS.ExpenseTracker.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TransferId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.HasIndex("TransferId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("RDS.ExpenseTracker.Domain.Entities.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("RDS.ExpenseTracker.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureOid")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDemo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AzureOid")
                        .IsUnique()
                        .HasFilter("[AzureOid] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RDS.ExpenseTracker.Domain.Entities.Account", b =>
                {
                    b.HasOne("RDS.ExpenseTracker.Domain.Entities.User", "UserNavigation")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("RDS.ExpenseTracker.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("RDS.ExpenseTracker.Domain.Entities.Account", "AccountNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RDS.ExpenseTracker.Domain.Entities.Category", "CategoryNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RDS.ExpenseTracker.Domain.Entities.Transfer", "TransferNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AccountNavigation");

                    b.Navigation("CategoryNavigation");

                    b.Navigation("TransferNavigation");
                });

            modelBuilder.Entity("RDS.ExpenseTracker.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RDS.ExpenseTracker.Domain.Entities.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RDS.ExpenseTracker.Domain.Entities.Transfer", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RDS.ExpenseTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
